run:
  timeout: 10m
  tests: true
  modules-download-mode: readonly

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/cert-manager/aws-privateca-issuer)
  goimports:
    local-prefixes: github.com/cert-manager/aws-privateca-issuer
  govet:
    check-shadowing: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - funlen
    - gci
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - gocognit
    # Exclude known linters from partially hard-to-fix issues
    - path: ".*"
      text: "weak cryptographic primitive"
      linters:
        - gosec
    # Exclude shadow checking on err variables in test files
    - path: _test\.go
      text: "shadow: declaration of \"err\""
      linters:
        - govet
  max-issues-per-linter: 0
  max-same-issues: 0