# permissions for end users to edit awspcaissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awspcaissuer-editor-role
rules:
- apiGroups:
  - awspca.cert-manager.io
  resources:
  - awspcaissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - awspca.cert-manager.io
  resources:
  - awspcaissuers/status
  verbs:
  - get
