name: Container
on:
  push:
    branches: master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: "startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'"
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push container images
        uses: docker/build-push-action@v2
        if: "github.ref == 'refs/heads/master'"
        with:
          context: .
          tags: ghcr.io/jniebuhr/aws-pca-issuer:latest
          push: true

      - name: Build and push container images
        uses: docker/build-push-action@v2
        if: "startsWith(github.ref, 'refs/tags/')"
        with:
          context: .
          tags: "ghcr.io/jniebuhr/aws-pca-issuer:${{ github.event.release.tag_name }}"
          push: true
