name: Release
on:
  push:
    tags:
      - *
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push container images
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ghcr.io/jniebuhr/aws-pca-issuer:latest
            ghcr.io/jniebuhr/aws-pca-issuer:${{ github.event.release.tag_name }}
          push: true

      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.CR_PAT }}
          app_version: ${{ github.event.release.tag_name }}
